create table public."Shop" (
  id bigint generated by default as identity primary key,
  name text not null
);

create table public."Customer" (
  id bigint generated by default as identity primary key,
  name text not null
);

create table public."Inventory" (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public."Shop"(id),
  cake_count integer not null default 0
);

create table public."Bank" (
  id bigint generated by default as identity primary key,
  balance numeric(12,2) not null default 0
);

create table public."Transaction" (
  id bigint generated by default as identity primary key,
  shop_id bigint not null references public."Shop"(id),
  customer_id bigint references public."Customer"(id),
  bank_id bigint references public."Bank"(id),
  type text not null,
  amount numeric(12,2) not null,
  created_at timestamptz not null default now()
);